# Generated by Django 4.1.3 on 2022-12-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_alter_like_post_alter_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
