export const GET_POSTS_BEGIN = 'GET_POSTS_BEGIN'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'

export const GET_PROFILE_POSTS_BEGIN = 'GET_PROFILE_POSTS_BEGIN'
export const GET_PROFILE_POSTS_SUCCESS = 'GET_PROFILE_POSTS_SUCCESS'

export const SHOW_PROFILE = 'SHOW_PROFILE'

export const TOGGLE_POST_MODAL = 'TOGGLE_POST_MODAL'
export const SET_POST_MODAL = 'SET_POST_MODAL'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const GET_OTHER_COMMENTS_SUCCESS = 'GET_OTHER_COMMENTS_SUCCESS'

export const CLEAR_STATES = 'CLEAR_STATES'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const TOGGLE_UPLOAD_MODAL = 'TOGGLE_UPLOAD_MODAL'

export const TOGGLE_OPTION_MODAL = 'TOGGLE_OPTION_MODAL'
export const HIDE_OPTION_MODAL = 'HIDE_OPTION_MODAL'

export const TOGGLE_EDIT_MODAL = 'TOGGLE_EDIT_MODAL'
