# Generated by Django 4.1.3 on 2022-12-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='img/default/ahri.jpg/', upload_to='img/avatar/'),
        ),
    ]
