# Generated by Django 4.1.3 on 2022-12-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
