# Generated by Django 4.1.3 on 2022-12-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0014_alter_post_image_url_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
